language: java
sudo: true
jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - chmod +x mvnw

script:
  - mvn clean install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
