language: java
jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - ./mvnw clean install
  - ./mvnw cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)